uicc0 = {    
         imsi = "208950000000032";

         key = "0C0A34601D4F07677303652C0462535B";
    
         opc= "63bfa50ee6523365ff14c1f45f88737d";
    
         nssai_sst=128;
    
         nssai_sd=128;
    
         dnn= "default";
    
         amf="8000";
    
         sqn="000000";
    
         nmc_size=2;
        }


